feat: Providing docker version
php-pds/skeleton pull request #55
Opened 2023-12-01 17:53 UTC by pablosanches

With this pull request we provide a docker version of skeleton

2023-12-08 16:33 UTC, pmjones requested changes
Thanks for the contribution, but unless there is some research to back up the recommendation, it's not appropriate for this publication.

2023-12-08 16:33 UTC, pmjones commented on README.md
> +| docker files                                   | `infra/`                   |
The problem here (and below) is that we have no research to back up this recommendation. All the other recommendations derive from <https://github.com/php-pds/skeleton_research>.

2023-12-11 10:37 UTC, pablosanches commented on README.md
> +| docker files                                   | `infra/`                   |
Thanks for the feedback, it's an honor to be able to contribute. The work done in the research repository is incredible. In the research repository, I found a zend framework skeleton that provides docker support and the "infra" path that I added does not actually qualify. I made the requested adjustments, I hope I got it right this time :)

Thank you very much for your attention!

2024-12-11 12:55 UTC, glensc commented
yeah, the pr title/body says docker, but actually there's dockerfile, makefile, and docker-compose

2024-12-26 11:07 UTC, closed without merging